### ISSUE TITLE
Hi Interesting article on the logger using msp430

### ISSUE THREAD

**Issue by amrithHN** [infinus-electronics/PIO-MSP430-Logger#1]
I thoroughly enjoyed your post on msp430 and data logger. I would like to connect on linkedln kindly send me a request or please share your handle . Are you currently studying in Cambridge?

This is not an issue :-) please close it.

**Comment by infinus-electronics** [comment]
Hello, glad you liked it!

my LinkedIn handle is hor-ye-heng-6a08a7143
